import { Stylist, ServiceCategory, Service, Review } from '../types/database';

export const stylists: Stylist[] = [
  {
    id: 's1',
    name: 'Melissa',
    role: 'Hair Stylist / Teacher',
    bio: 'With over 15 years of experience and a passion for education, Melissa combines technical expertise with creative flair. She specializes in precision cuts and color transformations.',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300&h=300&fit=crop',
    isActive: true,
  },
  {
    id: 's2',
    name: 'Mike',
    role: 'Salon Owner',
    bio: 'As the founder of Absolute Hair, Mike brings decades of industry experience and a commitment to excellence. He personally oversees all aspects of the salon to ensure the highest standards.',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&h=300&fit=crop',
    isActive: true,
  },
  {
    id: 's3',
    name: 'Laura',
    role: 'Senior Stylist',
    bio: 'Laura is a color specialist with an eye for detail and a love for creating beautiful, healthy hair. She stays ahead of trends while respecting timeless techniques.',
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=300&h=300&fit=crop',
    isActive: true,
  },
  {
    id: 's4',
    name: 'Mya',
    role: 'Stylist',
    bio: 'Mya brings energy and creativity to every appointment. She loves working with clients to create personalized looks that suit their lifestyle and personality.',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&h=300&fit=crop',
    isActive: true,
  },
  {
    id: 's5',
    name: 'Bella',
    role: 'Stylist',
    bio: 'Bella specializes in extensions and updos, creating stunning looks for special occasions and everyday glamour.',
    avatarUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=300&h=300&fit=crop',
    isActive: true,
  },
  {
    id: 's6',
    name: 'Ayla',
    role: 'Junior Stylist',
    bio: 'Ayla is our talented junior stylist, bringing fresh perspectives and the latest techniques to the team.',
    avatarUrl: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=300&h=300&fit=crop',
    isActive: true,
  },
];

export const serviceCategories: ServiceCategory[] = [
  { id: 'c1', salonId: '1', name: 'Haircuts', sortOrder: 1 },
  { id: 'c2', salonId: '1', name: 'Colour', sortOrder: 2 },
  { id: 'c3', salonId: '1', name: 'Highlights & Balayage', sortOrder: 3 },
  { id: 'c4', salonId: '1', name: 'Treatments', sortOrder: 4 },
  { id: 'c5', salonId: '1', name: 'Styling', sortOrder: 5 },
  { id: 'c6', salonId: '1', name: 'Add Ons', sortOrder: 6 },
];

export const services: Service[] = [
  // Haircuts
  {
    id: 'srv1',
    categoryId: 'c1',
    categoryName: 'Haircuts',
    name: 'Ladies Cut & Blow Dry',
    description: 'Precision haircut with professional blow dry finish',
    durationMinutes: 60,
    price: 45,
    hairLengthVariant: 'standard',
    isPopular: true,
    isActive: true,
  },
  {
    id: 'srv2',
    categoryId: 'c1',
    categoryName: 'Haircuts',
    name: 'Gents Cut',
    description: 'Professional mens haircut',
    durationMinutes: 30,
    price: 25,
    hairLengthVariant: 'standard',
    isPopular: false,
    isActive: true,
  },
  {
    id: 'srv3',
    categoryId: 'c1',
    categoryName: 'Haircuts',
    name: 'Child Cut (Under 12)',
    description: 'Haircut for children under 12',
    durationMinutes: 30,
    price: 20,
    hairLengthVariant: 'standard',
    isPopular: false,
    isActive: true,
  },
  {
    id: 'srv4',
    categoryId: 'c1',
    categoryName: 'Haircuts',
    name: 'Fringe Trim',
    description: 'Quick fringe/bang trim between cuts',
    durationMinutes: 15,
    price: 10,
    hairLengthVariant: 'standard',
    isPopular: false,
    isActive: true,
  },

  // Colour
  {
    id: 'srv5',
    categoryId: 'c2',
    categoryName: 'Colour',
    name: 'Full Head Colour',
    description: 'Complete color service from roots to ends',
    durationMinutes: 120,
    price: 65,
    hairLengthVariant: 'short_medium',
    isPopular: true,
    isActive: true,
  },
  {
    id: 'srv6',
    categoryId: 'c2',
    categoryName: 'Colour',
    name: 'Full Head Colour (Long/Thick)',
    description: 'Complete color service for long or thick hair',
    durationMinutes: 150,
    price: 85,
    hairLengthVariant: 'long_thick',
    isPopular: false,
    isActive: true,
  },
  {
    id: 'srv7',
    categoryId: 'c2',
    categoryName: 'Colour',
    name: 'Root Touch Up',
    description: 'Refresh your roots with precision color',
    durationMinutes: 90,
    price: 55,
    hairLengthVariant: 'standard',
    isPopular: true,
    isActive: true,
  },
  {
    id: 'srv8',
    categoryId: 'c2',
    categoryName: 'Colour',
    name: 'Toner',
    description: 'Enhance and refine your hair color',
    durationMinutes: 45,
    price: 35,
    hairLengthVariant: 'standard',
    isPopular: false,
    isActive: true,
  },

  // Highlights & Balayage
  {
    id: 'srv9',
    categoryId: 'c3',
    categoryName: 'Highlights & Balayage',
    name: 'Full Head Highlights',
    description: 'Beautiful dimensional highlights throughout',
    durationMinutes: 180,
    price: 95,
    originalPrice: 110,
    hairLengthVariant: 'short_medium',
    isPopular: true,
    isActive: true,
  },
  {
    id: 'srv10',
    categoryId: 'c3',
    categoryName: 'Highlights & Balayage',
    name: 'Full Head Highlights (Long/Thick)',
    description: 'Full highlights for long or thick hair',
    durationMinutes: 210,
    price: 125,
    hairLengthVariant: 'long_thick',
    isPopular: false,
    isActive: true,
  },
  {
    id: 'srv11',
    categoryId: 'c3',
    categoryName: 'Highlights & Balayage',
    name: 'Balayage',
    description: 'Hand-painted highlights for natural dimension',
    durationMinutes: 180,
    price: 105,
    hairLengthVariant: 'short_medium',
    isPopular: true,
    isActive: true,
  },
  {
    id: 'srv12',
    categoryId: 'c3',
    categoryName: 'Highlights & Balayage',
    name: 'Balayage (Long/Thick)',
    description: 'Premium balayage for long or thick hair',
    durationMinutes: 240,
    price: 145,
    originalPrice: 165,
    hairLengthVariant: 'long_thick',
    isPopular: false,
    isActive: true,
  },
  {
    id: 'srv13',
    categoryId: 'c3',
    categoryName: 'Highlights & Balayage',
    name: 'T-Section Highlights',
    description: 'Face-framing highlights around the hairline',
    durationMinutes: 120,
    price: 65,
    hairLengthVariant: 'standard',
    isPopular: false,
    isActive: true,
  },

  // Treatments
  {
    id: 'srv14',
    categoryId: 'c4',
    categoryName: 'Treatments',
    name: 'K18 Treatment',
    description: 'Revolutionary molecular repair treatment',
    durationMinutes: 30,
    price: 40,
    hairLengthVariant: 'standard',
    isPopular: true,
    isActive: true,
  },
  {
    id: 'srv15',
    categoryId: 'c4',
    categoryName: 'Treatments',
    name: 'Olaplex Treatment',
    description: 'Deep bond-building treatment for strength',
    durationMinutes: 45,
    price: 35,
    hairLengthVariant: 'standard',
    isPopular: true,
    isActive: true,
  },
  {
    id: 'srv16',
    categoryId: 'c4',
    categoryName: 'Treatments',
    name: 'Deep Conditioning Treatment',
    description: 'Intensive moisture and repair',
    durationMinutes: 30,
    price: 25,
    hairLengthVariant: 'standard',
    isPopular: false,
    isActive: true,
  },

  // Styling
  {
    id: 'srv17',
    categoryId: 'c5',
    categoryName: 'Styling',
    name: 'Blow Dry',
    description: 'Professional blow dry styling',
    durationMinutes: 45,
    price: 30,
    hairLengthVariant: 'short_medium',
    isPopular: false,
    isActive: true,
  },
  {
    id: 'srv18',
    categoryId: 'c5',
    categoryName: 'Styling',
    name: 'Blow Dry (Long/Thick)',
    description: 'Blow dry for long or thick hair',
    durationMinutes: 60,
    price: 40,
    hairLengthVariant: 'long_thick',
    isPopular: false,
    isActive: true,
  },
  {
    id: 'srv19',
    categoryId: 'c5',
    categoryName: 'Styling',
    name: 'Updo',
    description: 'Elegant upstyle for special occasions',
    durationMinutes: 90,
    price: 55,
    hairLengthVariant: 'standard',
    isPopular: false,
    isActive: true,
  },

  // Add Ons
  {
    id: 'srv20',
    categoryId: 'c6',
    categoryName: 'Add Ons',
    name: 'Scalp Massage',
    description: 'Relaxing scalp massage treatment',
    durationMinutes: 15,
    price: 10,
    hairLengthVariant: 'standard',
    isPopular: false,
    isActive: true,
  },
  {
    id: 'srv21',
    categoryId: 'c6',
    categoryName: 'Add Ons',
    name: 'Bond Booster',
    description: 'Add bond protection to any color service',
    durationMinutes: 0,
    price: 15,
    hairLengthVariant: 'standard',
    isPopular: false,
    isActive: true,
  },
];

export const reviews: Review[] = [
  {
    id: 'r1',
    bookingId: null,
    customerId: 'u1',
    stylistId: 's1',
    serviceName: 'Balayage',
    rating: 5,
    body: 'Melissa absolutely transformed my hair! The balayage is exactly what I wanted - natural, sun-kissed, and beautifully blended. The salon has a lovely atmosphere and everyone is so welcoming. Will definitely be returning!',
    ambienceRating: 5,
    cleanlinessRating: 5,
    staffRating: 5,
    isVerified: true,
    venueReply: 'Thank you so much for your kind words! We\'re thrilled you love your new look. See you next time!',
    createdAt: '2026-02-15T14:30:00Z',
    customerName: 'Sarah M.',
    stylistName: 'Melissa',
  },
  {
    id: 'r2',
    bookingId: null,
    customerId: 'u2',
    stylistId: 's3',
    serviceName: 'Full Head Colour',
    rating: 5,
    body: 'Laura is a true professional. She took the time to understand exactly what I wanted and the results are stunning. My hair feels healthier than ever thanks to the treatments she recommended.',
    ambienceRating: 5,
    cleanlinessRating: 5,
    staffRating: 5,
    isVerified: true,
    venueReply: null,
    createdAt: '2026-02-01T10:15:00Z',
    customerName: 'Emma T.',
    stylistName: 'Laura',
  },
  {
    id: 'r3',
    bookingId: null,
    customerId: 'u3',
    stylistId: 's2',
    serviceName: 'Ladies Cut & Blow Dry',
    rating: 5,
    body: 'Mike gave me the best haircut I\'ve had in years. He really listened to what I wanted and offered expert advice. The blow dry was gorgeous and lasted for days. Highly recommend!',
    ambienceRating: 5,
    cleanlinessRating: 5,
    staffRating: 5,
    isVerified: true,
    venueReply: 'Thank you! It was a pleasure working with you. We look forward to seeing you again soon.',
    createdAt: '2026-01-20T16:45:00Z',
    customerName: 'Rachel K.',
    stylistName: 'Mike',
  },
  {
    id: 'r4',
    bookingId: null,
    customerId: 'u4',
    stylistId: 's4',
    serviceName: 'Full Head Highlights',
    rating: 4,
    body: 'Great experience at Absolute Hair. Mya was friendly and skilled. My highlights look fantastic. The only reason I\'m not giving 5 stars is the parking can be tricky, but that\'s not the salon\'s fault!',
    ambienceRating: 4,
    cleanlinessRating: 5,
    staffRating: 5,
    isVerified: true,
    venueReply: null,
    createdAt: '2026-01-10T11:20:00Z',
    customerName: 'Jennifer L.',
    stylistName: 'Mya',
  },
  {
    id: 'r5',
    bookingId: null,
    customerId: 'u5',
    stylistId: 's1',
    serviceName: 'K18 Treatment',
    rating: 5,
    body: 'The K18 treatment is a game-changer! Melissa explained everything clearly and my hair has never felt softer or looked shinier. Worth every penny. The salon is immaculate and the team is wonderful.',
    ambienceRating: 5,
    cleanlinessRating: 5,
    staffRating: 5,
    isVerified: true,
    venueReply: 'We\'re so glad you\'re loving the K18! Thanks for trusting us with your hair care.',
    createdAt: '2025-12-28T13:00:00Z',
    customerName: 'Claire B.',
    stylistName: 'Melissa',
  },
];

